# Generated by Django 4.0.3 on 2022-04-13 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_subject_room_chat_host_message_room_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['created', 'updated']},
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
